###############################
# Storage Class
###############################
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
