apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy-ingress
  namespace: jitsi
spec:
  tls:
  - hosts:
    - c1-us-west1.meet.livestand.io
    secretName: meet-livestand-io-tls
  rules:
    - host: c1-us-west1.meet.livestand.io
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
              service:
                name: haproxy
                port:
                  number: 80

