apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- jitsi-namespace.yaml
- jitsi-secret.yaml
- prosody-configmap.yaml
- jvb-entrypoint-configmap.yaml
- jvb-shutdown-configmap.yaml
- web-configmap.yaml
- web-service.yaml

commonLabels:
  scope: jitsi
