apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy-ingress
  namespace: jitsi
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "<gcp_static_ip_name>"
spec:
  tls:
  - hosts:
    # fill in host here
    - jitsi.domainname
    secretName: meet-livestand-io-tls
